### ISSUE TITLE
Fix for multi-series tooltip

### ISSUE THREAD

**Issue by peacechen** [rudovjan/highcharts-tooltip-delay#10]
For charts that have multiple series, the tooltip delay method inadvertently cancels the timer for potentially valid events.  This is because _timerId_ is a single value when it needs to hold a separate value for each series.  This required a mild refactor:

    (function (H) {

        var timerId = {};

        H.wrap(H.Tooltip.prototype, 'refresh', function (proceed) {

            var seriesName = arguments[1].series.name;

            var delayForDisplay = this.chart.options.tooltip.delayForDisplay ? this.chart.options.tooltip.delayForDisplay : 1000;

            if (timerId[seriesName]) {
                clearTimeout(timerId[seriesName]);
                delete timerId[seriesName];
            }

            timerId[seriesName] = window.setTimeout(function () {
                var point = this.refreshArguments[0];

                if (point === this.chart.hoverPoint || $.inArray(this.chart.hoverPoint, point) > -1) {
                    proceed.apply(this.tooltip, this.refreshArguments);
                }

            }.bind({
                    refreshArguments: Array.prototype.slice.call(arguments, 1),
                    chart: this.chart,
                    tooltip: this
            }), delayForDisplay);
 
        });

    }(Highcharts));

_timerId_ has become an object, with the timer for each series stored as the series name key.  This allows each series' previous hover points to be canceled without affecting other series. 

Additionally, because the setTimeout callback may be called multiple times (once for each series), I set their context instead of relying exclusively on closures.

**Comment by rudovjan** [comment]
Fixed, thank you
