### ISSUE TITLE
Please add a package.json to your repo

### ISSUE THREAD

**Issue by nitoloz** [rudovjan/highcharts-tooltip-delay#11]
Hi

I am looking forward to use this great plugin for my app. The only thing that stops me is that I am using npm thus I am not able to start using this until there is no package.json file in your repo.
Could you please add package.json with minimum info?

Best regards,
Andrey

**Comment by rudovjan** [comment]
Hi Andrey,

Grat idea. Will do that this week.

Thanks,
Jan

**Comment by nitoloz** [comment]
Thank you, @rudovjan!
I am really loking forward to this improvement :)
