### ISSUE TITLE
Due to es6 syntax, uglify failures in project.

### ISSUE THREAD

**Issue by har1sh** [rudovjan/highcharts-tooltip-delay#12]
So i am trying to do a npm install which now pulls the new version 1.2.0, the build fails as i cant uglify the es6 syntax in the new code. Also if you could publish your work on npm that would be great, as with the package.json i can download it through git repo, but as its not versioned i am forced to get the latest always

**Comment by rudovjan** [comment]
Understand. Will either remove ES6 or will create dist version.

NPM publish is good idea.

**Comment by rudovjan** [comment]
It should be fixed.

https://www.npmjs.com/package/highcharts-tooltip-delay

https://github.com/rudovjan/highcharts-tooltip-delay/blob/master/tooltip-delay.dist.js

**Comment by har1sh** [comment]
Thank you
