### ISSUE TITLE
Default of 1000 is never used.

### ISSUE THREAD

**Issue by prettycode** [rudovjan/highcharts-tooltip-delay#3]
Here's what the code looks like:

    if (delayForDisplay) {
        window.setTimeout(function () {
            ...
        }, delayForDisplay || 1000);
    }
    ...

Because `if(delayForDisplay)` only executes if `delayForDisplay` is truthy, `delayForDisplay || 1000` will never `||` to `1000`.

**Comment by prettycode** [comment]
By the way, `$.inArray()` returning -1 is not a bug. In JavaScript, methods like `indexOf()` return `-1` if an element is not found in the array. :)

**Comment by rudovjan** [comment]
Thank you!

**Comment by Cornally** [comment]
I ran into an edge case today where I wanted to "opt out" of the delay entirely yet preserve it elsewhere for a different chart.  I'll push another version after further testing where you can explicitly bypass the delay by passing `delayforDisplay: false`. A forced default delay might not be desirable for some. 

Cheers!

**Comment by prettycode** [comment]
I made the same change myself. If `delayForDisplay === false`, then execute the original prototype immediately. :)

**Comment by Cornally** [comment]
Good stuff!  I pushed a new version to my fork this morning along with an update to the documentation.  Thanks again.
