### ISSUE TITLE
If tooltip is shared then tooltipdelay feature doesn't work correctly.

### ISSUE THREAD

**Issue by rspandi1985** [rudovjan/highcharts-tooltip-delay#5]
Hi, Check this example.
http://jsfiddle.net/5r6pmt44/

If tooltip is shared and then you hide all series except 1, Let's say for ex- Hide all except Tokyo series. Now mouse hover on each point you will see tooltip appears for previous point and not for current mousehover point.

**Comment by rudovjan** [comment]
True.. :-/ Am looking on it

**Comment by rudovjan** [comment]
For now it's disabled for shared tooltip, there is some weird logic happening.. Will try later

**Comment by Drumstix42** [comment]
Any updates on this issue?

**Comment by rudovjan** [comment]
Sorry guys for delay. Solved. It took me time realize what's unique key for group of points. This patch should fix it. Could have issue with big amount of points (100000+) in one tooltip.. but that's unfortunate situation.
