### ISSUE TITLE
Add an "initialDelay" option

### ISSUE THREAD

**Issue by haridsv** [rudovjan/highcharts-tooltip-delay#6]
IMHO, the delay is more useful for the initial show such that it is not triggered inadvertently. If the tooltip is already visible, the subsequent hovers should update it with no delay. Having a separate option called `initialDelay` will be helpful in this regard.

**Comment by rudovjan** [comment]
It really depends on situation. With latest push, it's now exact 1s before tooltip is shown. Your description is actually what this plugin was doing before.
