### ISSUE TITLE
Do not show tooltip if mouseout before delay ends

### ISSUE THREAD

**Issue by hagen** [rudovjan/highcharts-tooltip-delay#7]
It seems a tooltip delay is useful in cases where there are many series on a chart; in such scenarios, I'd like to see an option to prevent display of the tooltip if the user has moused out **before** the delay is completed - in this way, you can mouse around on the chart without a tooltip following you everywhere, unless you explicitly wait around above a Point.

**Comment by rudovjan** [comment]
I think this is solved with last change introduced @peacechen
